apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "edge-gateway.fullname" . }}
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.hostname }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.allowedRoutes.namespaces.from }}
          selector:
            matchLabels:
              {{- toYaml .Values.allowedRoutes.namespaces.selector.matchLabels | nindent 14 }}
