apiVersion: v2
name: argo-cd
description: Wrapper chart for the Argo CD upstream Helm chart.
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 9.5.15
    repository: https://argoproj.github.io/argo-helm
