# KinD environment overrides for backstage chart.
# These values are for local development only — do not use for other environments.
image:
  repository: localhost:5001/backstage
  pullPolicy: IfNotPresent

github:
  auth:
    create: false
    existingSecret: backstage-github-token

postgres:
  enabled: true
  auth:
    create: true
    password: hunter2

appConfig:
  catalog:
    locations:
      - type: url
        target: https://github.com/Itamar-Ratson/backstage-k8s-full/blob/main/**/catalog-info.yaml
