# Dev environment overrides for backstage chart.
# These values are for local development only - do not use for other environments.
image:
  repository: ghcr.io/itamar-ratson/backstage-k8s-full/backstage
  tag: "f8a0c87"
  pullPolicy: IfNotPresent
github:
  auth:
    create: false
    existingSecret: backstage-github-app
oauth:
  github:
    create: false
    existingSecret: backstage-github-app
postgres:
  enabled: true
  auth:
    create: true
    password: hunter2
rbac:
  policies: |
    p, role:default/viewer, catalog-entity, read, allow
    p, role:default/viewer, catalog.location.read, read, allow
    p, role:default/viewer, catalog-location, read, allow
    p, role:default/viewer, scaffolder.template.parameter.read, read, allow
    p, role:default/viewer, scaffolder.template.step.read, read, allow
    p, role:default/viewer, scaffolder-template, read, allow
    p, role:default/viewer, scaffolder-action, read, allow
    p, role:default/viewer, scaffolder-parameter, read, allow
    p, role:default/viewer, scaffolder-step, read, allow
    p, role:default/viewer, techdocs-metadata, read, allow
    p, role:default/viewer, techdocs-content, read, allow
    p, role:default/viewer, kubernetes.proxy, use, allow
    p, role:default/viewer, kubernetes.resources.read, read, allow
    p, role:default/viewer, kubernetes.clusters.read, read, allow
    p, role:default/viewer, kubernetes-proxy, use, allow
    p, role:default/viewer, search-query, read, allow
    p, role:default/platform-admin, catalog-entity, read, allow
    p, role:default/platform-admin, catalog-entity, create, allow
    p, role:default/platform-admin, catalog-entity, update, allow
    p, role:default/platform-admin, catalog-entity, delete, allow
    p, role:default/platform-admin, catalog.entity.create, create, allow
    p, role:default/platform-admin, catalog.entity.validate, use, allow
    p, role:default/platform-admin, catalog-location, read, allow
    p, role:default/platform-admin, catalog-location, create, allow
    p, role:default/platform-admin, catalog-location, delete, allow
    p, role:default/platform-admin, catalog.location.analyze, use, allow
    p, role:default/platform-admin, scaffolder-template, read, allow
    p, role:default/platform-admin, scaffolder-action, use, allow
    p, role:default/platform-admin, scaffolder-task, read, allow
    p, role:default/platform-admin, scaffolder-task, use, allow
    p, role:default/platform-admin, scaffolder.task.create, create, allow
    p, role:default/platform-admin, scaffolder.template.management, use, allow
    p, role:default/platform-admin, techdocs-metadata, read, allow
    p, role:default/platform-admin, techdocs-content, read, allow
    p, role:default/platform-admin, kubernetes.proxy, use, allow
    p, role:default/platform-admin, kubernetes.resources.read, read, allow
    p, role:default/platform-admin, kubernetes.clusters.read, read, allow
    p, role:default/platform-admin, kubernetes-proxy, use, allow
    p, role:default/platform-admin, search-query, read, allow
    p, role:default/platform-admin, policy-entity, read, allow
    p, role:default/platform-admin, policy-entity, update, allow
    p, role:default/platform-admin, policy-entity, delete, allow
    p, role:default/platform-admin, policy.entity.create, create, allow
    g, user:default/guest, role:default/viewer
    g, user:development/guest, role:default/viewer
appConfig:
  kubernetes:
    serviceLocatorMethod:
      type: multiTenant
    clusterLocatorMethods:
      - type: config
        clusters:
          - name: local
            url: https://kubernetes.default.svc.cluster.local
            authProvider: serviceAccount
            skipTLSVerify: false
    customResources:
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: gateways
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: httproutes
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: gatewayclasses
  techdocs:
    builder: local
    generator:
      runIn: local
    publisher:
      type: local
  auth:
    providers:
      github:
        development:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
  integrations:
    github:
      - host: github.com
        apps:
          - appId: ${APP_ID}
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            privateKey: ${PRIVATE_KEY}
  platform:
    githubOwner: ${GITHUB_OWNER}
    githubRepo: ${GITHUB_REPO}
    ghcrBase: ${GHCR_BASE}
  permission:
    rbac:
      policies-csv-file: /etc/backstage/rbac/rbac-policies.csv
  catalog:
    locations:
      - type: url
        target: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/blob/main/**/*catalog-info.yaml
      - type: file
        target: /etc/backstage/rbac/users.yaml
