# Dev environment overrides for backstage chart.
# These values are for local development only - do not use for other environments.
image:
  repository: ghcr.io/itamar-ratson/backstage-k8s-full/backstage
  tag: ""
  pullPolicy: IfNotPresent

github:
  auth:
    create: false
    existingSecret: backstage-github-token

oauth:
  github:
    create: false
    existingSecret: backstage-github-oauth

postgres:
  enabled: true
  auth:
    create: true
    password: hunter2

appConfig:
  kubernetes:
    serviceLocatorMethod:
      type: multiTenant
    clusterLocatorMethods:
      - type: config
        clusters:
          - name: local
            url: https://kubernetes.default.svc.cluster.local
            authProvider: serviceAccount
            skipTLSVerify: false
    customResources:
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: gateways
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: httproutes
      - group: gateway.networking.k8s.io
        apiVersion: v1
        plural: gatewayclasses
  techdocs:
    builder: local
    generator:
      runIn: local
    publisher:
      type: local
  auth:
    providers:
      github:
        development:
          clientId: ${AUTH_GITHUB_CLIENT_ID}
          clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
  permission:
    rbac:
      admin:
        users:
          - name: user:default/itamar-ratson
      policies-csv-file: /etc/backstage/rbac-policies.csv
  catalog:
    locations:
      - type: url
        target: https://github.com/Itamar-Ratson/backstage-k8s-full/blob/main/**/catalog-info.yaml
      - type: file
        target: /etc/backstage/users.yaml
