gateway-helm:
  crds:
    gatewayAPI:
      enabled: true
      channel: standard
    envoyGateway:
      enabled: true
  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      provider:
        type: Kubernetes
      logging:
        level:
          default: info

gatewayClass:
  enabled: true
  name: eg-lb
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system

envoyProxy:
  enabled: true
  name: custom-proxy-config
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        patch:
          type: StrategicMerge
          value:
            spec:
              externalTrafficPolicy: Cluster
              ipFamilies: [IPv4]
              loadBalancerIP: 172.18.0.250
              ports:
                - port: 80
                  protocol: TCP
