apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-ci
  description: test
  annotations:
    backstage.io/managed-by-template: ci-pipeline
    backstage.io/source-paths: '[".github/workflows/caller-hello-world.yaml","deploy/dev/hello-world.yaml","deploy/dev/hello-world.catalog-info.yaml"]'
    backstage.io/source-location: url:https://github.com/Itamar-Ratson/backstage-k8s-full/blob/main/.github/workflows/caller-hello-world.yaml
    github.com/project-slug: Itamar-Ratson/backstage-k8s-full
  links:
    - title: Workflow runs
      url: https://github.com/Itamar-Ratson/backstage-k8s-full/actions/workflows/caller-hello-world.yaml
      icon: github
spec:
  type: ci-pipeline
  lifecycle: experimental
  owner: user:default/itamar-ratson
  system: system:default/developer-portal
