apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: {{ .Values.repoURL | quote }}
        revision: {{ .Values.targetRevision | quote }}
        directories:
          - path: charts/workloads/*
  template:
    metadata:
      name: '{{ "{{.path.basename}}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL | quote }}
        targetRevision: {{ .Values.targetRevision | quote }}
        path: '{{ "{{.path.path}}" }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - /deploy/dev/{{ "{{.path.basename}}" }}.yaml
          valuesObject:
            image:
              repository: {{ printf "%s/{{.path.basename}}" .Values.ghcrBase | quote }}
            rbac:
              adminUser: {{ .Values.rbacAdminUser | quote }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{.path.basename}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
