---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sealed-secrets
  description: Sealed Secrets controller for decrypting GitOps-managed workload secrets.
  annotations:
    backstage.io/kubernetes-id: sealed-secrets
spec:
  type: service
  lifecycle: production
  owner: platform
  system: platform
