apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Itamar-Ratson/backstage-k8s-full.git
        revision: main
        directories:
          - path: charts/workloads/*
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/Itamar-Ratson/backstage-k8s-full.git
        targetRevision: main
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - /deploy/dev/{{.path.basename}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
