apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kagent
  description: kagent
  annotations:
    backstage.io/managed-by-template: application
    backstage.io/source-paths: '["charts/workloads/kagent"]'
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kagent'
spec:
  type: helm-chart
  lifecycle: experimental
  owner: user:default/itamar
  system: system:default/developer-portal
