nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ghcr.io/kagent-dev/kagent/helm/kagent
  tag: 0.9.4
  pullPolicy: IfNotPresent

host: kagent.localtest.me
port: 80

gateway:
  name: edge-gateway
  namespace: gateway

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
