apiVersion: v2
name: podinfo
description: podinfo
type: application
version: 0.1.0
dependencies:
  - name: podinfo
    version: 6.12.0
    repository: oci://ghcr.io/stefanprodan/charts
    alias: app
