apiVersion: v2
name: podinfo
description: podinfo
type: application
version: 0.1.0
dependencies:
  - name: podinfo
    version: sha256-935725a423a7ca5d7f5f9a850d152b80938528d0d4f209dd1ce66a3bc0ddea92
    repository: oci://ghcr.io/stefanprodan/charts
    alias: app
