image:
  repository: backstage
  tag: ""
  pullPolicy: Always
  pullSecrets: []

serviceAccount:
  annotations: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

probes:
  enabled: false
  readiness:
    path: /healthcheck
    port: 7007
  liveness:
    path: /healthcheck
    port: 7007

service:
  port: 80
  targetPort: http

github:
  auth:
    create: true
    existingSecret: ""
    token: ""

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "13.2-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 2Gi
  auth:
    create: true
    existingSecret: ""
    username: backstage
    password: ""
    database: backstage
    host: postgres
    port: "5432"

gateway:
  name: edge-gateway
  namespace: gateway

hostname: backstage.localtest.me
