image:
  repository: backstage
  tag: ""
  pullPolicy: Always
  pullSecrets: []

serviceAccount:
  annotations: {}

kubernetes:
  rbac:
    # Disable when cluster RBAC is provisioned externally by platform admins.
    enabled: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

probes:
  enabled: false
  readiness:
    path: /healthcheck
    port: 7007
  liveness:
    path: /healthcheck
    port: 7007

service:
  port: 80
  targetPort: http

github:
  auth:
    create: false
    existingSecret: ""
    token: ""

oauth:
  github:
    create: false
    existingSecret: backstage-github-oauth
    clientId: ""
    clientSecret: ""

rbac:
  policies: ""
  users: ""

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "13.2-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    size: 2Gi
  auth:
    create: true
    existingSecret: ""
    username: backstage
    password: ""
    database: backstage
    host: postgres
    port: "5432"

gateway:
  name: edge-gateway
  namespace: gateway

hostname: backstage.localtest.me

appConfig:
  app:
    baseUrl: http://backstage.localtest.me:8080
  backend:
    baseUrl: http://backstage.localtest.me:8080
    listen: ":7007"
    csp:
      upgrade-insecure-requests: false
    database:
      client: pg
      connection:
        host: ${POSTGRES_HOST}
        port: ${POSTGRES_PORT}
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
  auth:
    providers:
      guest:
        dangerouslyAllowOutsideDevelopment: true
  catalog:
    rules:
      - allow: [Component, System, API, Resource, Location, Domain, User, Group, Template]
    locations: []
