apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-app-config
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  app-config.runtime.yaml: |
    {{- .Values.appConfig | toYaml | nindent 4 }}
  rbac-policies.csv: |
    {{- .Values.rbac.policies | nindent 4 }}
  users.yaml: |
    {{- .Values.rbac.users | nindent 4 }}
