apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-postgres
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | b64enc }}
  POSTGRES_HOST: {{ .Values.postgres.auth.host | b64enc }}
  POSTGRES_PORT: {{ .Values.postgres.auth.port | b64enc }}
