apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-github
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.github.auth.token | b64enc }}
