{{- if .Values.github.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-github
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ required "github.auth.token is required when github.auth.create=true" .Values.github.auth.token | b64enc }}
{{- end }}
