nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image: nginx:latest

host: test-03.localtest.me
port: 80

gateway:
  name: edge-gateway
  namespace: gateway

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
