apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-01
  description: test
  annotations:
    backstage.io/managed-by-template: application
    backstage.io/source-paths: '["charts/workloads/test-01"]'
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/Itamar-Ratson/backstage-k8s-full/tree/main/charts/workloads/test-01/
    github.com/project-slug: Itamar-Ratson/backstage-k8s-full
    backstage.io/kubernetes-id: test-01
spec:
  type: helm-chart
  lifecycle: experimental
  owner: platform
  system: system:default/developer-portal
