nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: docker.io/library/nginx
  tag: latest
  pullPolicy: IfNotPresent

host: test-01.localtest.me
port: 80

gateway:
  name: edge-gateway
  namespace: gateway

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
