apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-rbac
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  rbac-policies.csv: |
    {{- .Values.rbac.policies | trimSuffix "\n" | nindent 4 }}
    {{- if .Values.rbac.adminUser }}
    g, user:default/{{ .Values.rbac.adminUser }}, role:default/platform-admin
    {{- end }}
  users.yaml: |
    {{- if .Values.rbac.adminUser }}
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: {{ .Values.rbac.adminUser }}
    spec:
      profile:
        displayName: {{ .Values.rbac.adminUser }}
      memberOf: []
    {{- else }}
    {{- .Values.rbac.users | trimSuffix "\n" | nindent 4 }}
    {{- end }}
