apiVersion: v1
kind: ConfigMap
{{- $rbacAdminUser := .Values.rbac.adminUser }}
{{- $rbacAdminEntityRef := printf "user:default/%s" $rbacAdminUser }}
metadata:
  name: {{ include "backstage.fullname" . }}-rbac
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  rbac-policies.csv: |
    {{- .Values.rbac.policies | trimSuffix "\n" | nindent 4 }}
    {{- if $rbacAdminUser }}
    g, {{ $rbacAdminEntityRef }}, role:default/platform-admin
    {{- end }}
  users.yaml: |
    {{- if $rbacAdminUser }}
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: {{ $rbacAdminUser }}
    spec:
      profile:
        displayName: {{ $rbacAdminUser }}
      memberOf: []
    {{- else }}
    {{- .Values.rbac.users | trimSuffix "\n" | nindent 4 }}
    {{- end }}
