name: Build hello-world Image

on:
  push:
    branches:
      - main
    paths:


      - hello-world/**



permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  issues: write

jobs:
  build:
    name: Build hello-world
    uses: ./.github/workflows/build-image.yaml
    with:
      app-name: hello-world
      context: hello-world
      dockerfile: hello-world/Dockerfile
      bump-file: deploy/dev/hello-world.yaml
      bump-yaml-path: .image.tag
